version: "3"

services:
  postgres:
    image: "postgres:13.2"
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=issuehut
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: "redis:6.2.1"
    ports:
      - "6379:6379"

  adminer:
    depends_on:
      - postgres
    image: adminer
    restart: always
    ports:
      - 8080:8080
