version: "3.1"

services:
  postgres:
    image: "postgres:13.2"
    container_name: "postgres"
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: "redis:6.2.1"
    container_name: "redis"
    restart: always
    ports:
      - 6379:6379

  adminer:
    image: adminer
    depends_on:
      - postgres
    container_name: "adminer"
    restart: always
    ports:
      - 8080:8080
